events {}
http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 80; # Puerto interno de Nginx
        server_name localhost;

        # 1. Servir el frontend (archivos HTML/CSS/JS)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # 2. Redireccionamiento Inverso (API Gateway)
        # Cuando el frontend llame a /api/predict
        location /api/ {
            # Habilitar CORS
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            
            # Quitar /api/ antes de enviar al backend
            rewrite ^/api/(.*)$ /$1 break; 
            
            # Enviar la solicitud internamente al servicio 'backend'
            proxy_pass http://backend:5000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}